# Generated by Django 2.1.5 on 2019-01-08 02:57

from django.db import migrations, models
import isps.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('lowest_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_speed', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to=isps.models.Provider.user_directory_path)),
                ('url', models.URLField(max_length=254)),
            ],
        ),
    ]
