# Generated by Django 2.1.5 on 2019-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(),
        ),
    ]
