# Generated by Django 2.1.5 on 2019-01-09 02:51

from django.db import migrations, models
import isps.models


class Migration(migrations.Migration):

    dependencies = [
        ('isps', '0002_auto_20190108_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=isps.models.Provider.user_directory_path),
        ),
    ]
